### ISSUE TITLE
SpoonUtils#initAdb fails if AndroidDebugBridge is already initialized

### ISSUE THREAD

**Issue by yomik** [square/spoon#203]
This started occurring after upgrading the android gradle plugin to 0.13.1 (gradle 2.1) :

IllegalStateException : AndroidDebugBridge.init() has already been called.
Occurring in AndroidDebugBridge.init().

Currently using https://github.com/stanfy/spoon-gradle-plugin to run spoon as part of a jenkins automated build process. The plugin uses SpoonRunner.Builder, which fails when run() is called.

Though this used to happen before if connectedAndroidTest task was called before spoon task, it now happens without any other tasks declared.

AndroidDebugBridge does not provide with a getter for sInitialized, so the only way to detect this would be to try catch on IllegalStateException.

**Comment by commjoen** [comment]
we are experiencing the same problem here (using the 1.1.2 android gradle plugin), using the same external spoon-gradle-plugin from stanfy.

**Comment by edenman** [comment]
@yomik @commjoen this doesn't seem to happen on 1.0.0, so I'm going to close this out.  Re-open if you're still having problems.

**Comment by yomik** [comment]
The problem is still present; this is what I get :
```Caused by: java.lang.IllegalStateException: AndroidDebugBridge.init() has already been called.
	at com.android.ddmlib.AndroidDebugBridge.init(AndroidDebugBridge.java:203)
	at com.squareup.spoon.SpoonUtils.initAdb(SpoonUtils.java:100)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:79)
	at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:132)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
```

I'm running spoon 1.1.5 and stanfy spoon-gradle-plugin 0.14.1.
Could it be a problem related to spoon-gradle-plugin rather than spoon itself ?

**Comment by edenman** [comment]
That seems pretty unlikely.  Do you by any chance have multiple instrumentation test projects in your build?  If so, you're probably seeing #82 which I think I just fixed earlier today.  You can try to confirm by following the steps here (or just wait for a new spoon-gradle-plugin release with the update in it): https://github.com/square/spoon/issues/82#issuecomment-82002468

**Comment by roman-mazur** [comment]
I'm pretty sure this can happen if you run multiple spoon runner tasks in parallel. Each task will be calling `AndroidDebugBridge.init()` and `AndroidDebugBridge.terminate()` on their own.

**Comment by roman-mazur** [comment]
Generally how we use `AndroidDebugBridge` API sparks a lot of problems. This one IMO is also related https://github.com/stanfy/spoon-gradle-plugin/issues/4

**Comment by yomik** [comment]
@edenman I only have one project with instrumentation tests. I tried using a locally installed version of the spoon gradle plugin 0.14.2-SNAPSHOT but the issue remains.

**Comment by roman-mazur** [comment]
Note that Android plugin seems to use it in a different way.
Here's how they initialize https://android.googlesource.com/platform/tools/base/+/gradle_1.1.3/build-system/builder/src/main/java/com/android/builder/testing/ConnectedDeviceProvider.java#60
and I do not see any place where `terminate()` is called (despite that fact it's documented that this method must be called).
